name: Build and Release Packages

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Build packages
      run: pnpm run build --filter=@elevenlabs/client --filter=@elevenlabs/react
      
    - name: Create tarballs
      run: |
        cd packages/client && pnpm pack
        cd ../react && pnpm pack
        
    - name: Generate release tag
      id: tag
      run: |
        # Create a tag based on timestamp and short commit hash
        TAG="v$(date +%Y%m%d-%H%M%S)-$(git rev-parse --short HEAD)"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "Generated tag: $TAG"
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        release_name: "Auto-build ${{ steps.tag.outputs.tag }}"
        body: |
          Automated build from commit ${{ github.sha }}
          
          ## Install in your project:
          
          ```bash
          npm install https://github.com/${{ github.repository }}/releases/download/${{ steps.tag.outputs.tag }}/elevenlabs-react-0.6.2.tgz
          ```
          
          Or in package.json:
          ```json
          {
            "dependencies": {
              "@elevenlabs/react": "https://github.com/${{ github.repository }}/releases/download/${{ steps.tag.outputs.tag }}/elevenlabs-react-0.6.2.tgz"
            }
          }
          ```
        draft: false
        prerelease: false
        
    - name: Upload Client Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./packages/client/elevenlabs-client-0.6.2.tgz
        asset_name: elevenlabs-client-0.6.2.tgz
        asset_content_type: application/gzip
        
    - name: Upload React Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./packages/react/elevenlabs-react-0.6.2.tgz
        asset_name: elevenlabs-react-0.6.2.tgz
        asset_content_type: application/gzip
        
    - name: Output URLs
      run: |
        echo "🎉 Release created successfully!"
        echo "📦 React Package URL: https://github.com/${{ github.repository }}/releases/download/${{ steps.tag.outputs.tag }}/elevenlabs-react-0.6.2.tgz"
        echo "📦 Client Package URL: https://github.com/${{ github.repository }}/releases/download/${{ steps.tag.outputs.tag }}/elevenlabs-client-0.6.2.tgz"
